apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: {{ .Release.Namespace }}
data:
  service.json: |
    {
      "kernelCaps": [ "SYS_ADMIN" ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quota
  namespace: {{ .Release.Namespace }}
data:
{{- range $k,$v := .Values.quota }}
  {{ $k }}.json: |
    {{- if $.Values.extraQuota }}
      {{ merge $v (index $.Values.extraQuota $k) | toJson }}
    {{- else }}
      {{ $v | toJson }}
    {{- end }}
{{- end }}
